### PR TITLE
fix: remove prefixes from paths in mint.json

### PR DESCRIPTION
**Pull request by rpmccarter**
Several fielpaths must have changed, and their corresponding nav entries did not. We still need to fix syntax errors on a few pages and add some new files to the nav, but this should fix the majority of pages

### CODE REVIEW

**Comment by elephaint** [comment]
@rpmccarter Thanks - I think this is due to an earlier merge conflict that did not surface. Agree that the fix should work, let me check whether if we merge our latest changes (which include a set of other changes too) this will be fixed automatically too.

**Comment by jmoralez** [comment]
Also this PR should target [this file](https://github.com/Nixtla/nixtla/blob/main/nbs/mint.json) in the main branch.

**Comment by elephaint** [comment]
I think if we merge #329 this will also be fixed

**Comment by elephaint** [comment]
> Several fielpaths must have changed, and their corresponding nav entries did not. We still need to fix syntax errors on a few pages and add some new files to the nav, but this should fix the majority of pages

Out of interest, why are prefixes removed from filenames by Mintlify? Is that defined somewhere? Because it feels quite weird....

**Comment by elephaint** [comment]
@rpmccarter We implemented these changes but it still doesn't render. Can you look at the [logs of build_docs](https://github.com/Nixtla/nixtla/actions/runs/8944367130/job/24571136068) and see what goes wrong? There is no error there, so I'd assume the files are built properly.

**Comment by mergenthaler** [comment]
@elephaint, is this already fixed? If yes, please feel free to close this PR.

**Comment by elephaint** [comment]
Yes, this has been fixed already.

**Pull request closed without merging**
