### PR TITLE
docs: FAQ | formatting fix

### PR DESCRIPTION
**Pull request by ngupta23**
## Changes Made

* Fixed bullet formatting in FAQs
* Fixed instructions in CONTRIBUTING.md

### FAQ formatting

**Current website:**

https://docs.nixtla.io/docs/getting-started-faq#pricing-and-billing

image

**Fixed formatting**

image

### CODE REVIEW

**Comment by jmoralez** [comment]
* Please include links in the description, it takes time to figure out where that screenshot comes from.
* This should be `docs(FAQ)`, not `fix`.
* Add the corresponding label to the PR (documentation).
* This can be tested, why should we merge a "possible" fix?

**Comment by elephaint** [comment]
Thanks @ngupta23 for the PR! I agree with @jmoralez, the PR would benefit from some clarifications. You can test locally on [Mintlify following this](https://mintlify.com/docs/development). If that doesn't work for you (it is finnicky), I'd find a comparable docs page where we also have bullets and use the formatting we see there, to fix this error.

**Comment by ngupta23** [comment]
Thanks for the feedback and pointers. I will have a look at them.

**Comment by ngupta23** [comment]
Thanks @elephaint for guiding me through the process. I have made the suggested changes by both of you. Please review. Thanks!

**Review by jmoralez — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
