### PR TITLE
[DOCS] - Add a welcome/introduction page to the documentation

### PR DESCRIPTION
**Pull request by marcopeix**
This a first draft of an introduction/welcome page for the documentation of TimeGPT.

We can probably improve the wording, make it more exciting. 

Waiting for the final structure to include hyperlinks.

### CODE REVIEW

**Comment by mergenthaler** [comment]
This is good for a first draft. Lets mark this as ready for review.

**Review by mergenthaler — APPROVED** [review]
LGTM as a first draft. Lets publish and iterate.

**Comment by mergenthaler** [comment]
@AzulGarza, this is ready to review.

**Review by AzulGarza — CHANGES_REQUESTED** [review]
thanks @marcopeix, could you please update this pr as well?

**Review by AzulGarza — APPROVED** [review]
awesome @marcopeix! lgtm

**Pull request merged**
