### PR TITLE
Add capabilities notebooks

### PR DESCRIPTION
**Pull request by marcopeix**
Forecast capabilities notebooks. 

Anomaly detection notebooks are done too.

### CODE REVIEW

**Review by mergenthaler — APPROVED** [review]
Thanks! Great additions.

**Comment by mergenthaler** [comment]
@AzulGarza, this is ready for review.

**Review by AzulGarza — CHANGES_REQUESTED** [review]
thanks @marcopeix! could you please update this pr with the new structure of the docs? it is already merged in main :)

**Comment by marcopeix** [comment]
> thanks @marcopeix! could you please update this pr with the new structure of the docs? it is already merged in main :)

I see quickstart notebooks already in each section of capabiltiies. Do I keep those in the PR or remove them?

**Review by AzulGarza — APPROVED** [review]

**Pull request merged**
