### PR TITLE
[DOC] - Add links and callouts

### PR DESCRIPTION
**Pull request by marcopeix**
Add links in page "About TimeGPT"
Add links in sections of capabilities. The links go to the notebooks in capabilities.
Add callouts for TimeGPT on Azure in all capabilities notebooks and tutorial 01 to 08.

### CODE REVIEW

**Review by AzulGarza — CHANGES_REQUESTED** [review]
thanks @marcopeix! i deployed the readme dot com version from this branch. 

could we fix the following? 

1.  the lists of the sections rendered this way:

image

i think we can use multiple breaklines as in the previous docs:

```

* [Simple anomaly detection](https://docs.nixtla.io/docs/capabilities-anomaly-detection-quickstart)

* [Anomaly detection with exogenous features](https://docs.nixtla.io/docs/capabilities-anomaly-detection-add_exogenous_variables)

...
```

2. also, when instantiating the `NixtlaClass`, we have the following:

image

i think this one can be solved also adding some breaklines:

```
 nixtla_client = NixtlaClient(
 
    base_url="you azure ai endpoint",
    
    api_key="your api_key",
    
)
```

the last one looks pretty cool!

image

**Comment by AzulGarza** [comment]
hey @marcopeix! just reviewed #357, and saw that @elephaint used the readme dot com callout style, and i think it looks very cool, wdyt if we use that? please see https://github.com/Nixtla/nixtla/pull/357#pullrequestreview-2056655739.

image

**Comment by marcopeix** [comment]
Fixed layout issues and used the readme.com style for callouts

**Review by AzulGarza — APPROVED** [review]
thank you @marcopeix! lgtm

**Pull request merged**
