### PR TITLE
Update timegpt.py

### PR DESCRIPTION
**Pull request by akashgoyal2110**
ISSUE-116 - Resolved checking of the target and exogenous variables in X_df dataframe

### CODE REVIEW

**Comment by akashgoyal2110** [comment]
I have made the required changes to the '_validate_inputs' function to incorporate validation for target and exogenous variables in X_df dataframe.

**Review by AzulGarza — CHANGES_REQUESTED** [review]
Hey @akashgoyal2110! Thank you! In this repo, we use `nbdev` to generate `nixtlats/timegpt.py`. [Here](https://github.com/Nixtla/how-to-contribute-nixtlaverse)'s a step-by-step guide. Could you update the PR following the tutorial there? Thank you!

**Comment by mergenthaler** [comment]
@elephaint, please see if this can be closed with your new docs.

**Comment by elephaint** [comment]
> @elephaint, please see if this can be closed with your new docs.

Do you mean you want to just state the required numeric types in the docs or include the fix in the doc PR? 

This fix isn't complete btw, e.g. what happens with datetime dtypes for y, or complex dtypes, all edge cases that are not covered by the proposed solution. I do have a fix for that (I can modify this PR). Let me know.

**Comment by AzulGarza** [comment]
@elephaint thanks. let's try to fix #116 in a new pr.

**Pull request closed without merging**
