### PR TITLE
feat: Added Dask and Ray how-to-guides

### PR DESCRIPTION
**Pull request by MMenchero**
Related to issue #144.

### CODE REVIEW

**Review by AzulGarza — CHANGES_REQUESTED** [review]
Thank you, @MMenchero! Could we change the name of the files? They should be enumerated, eg:

- `0_distributed_fcst_spark...`
- `1_distributed_cv_spark...`
- `2_distributed_fcst_dask...`
- `3_distributed_cv_daks...`

And so on :)

**Comment by AzulGarza** [comment]
thank you @MMenchero, could you please remove the duplicated files?

**Review by AzulGarza — APPROVED** [review]
nice @MMenchero!😍

**Comment by MMenchero** [comment]
This PR was updated to  #301.

**Pull request closed without merging**
